### ISSUE TITLE
Update Python to 3.8

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via3#444]
For: https://github.com/hypothesis/product-backlog/issues/1199

This requires updates to:

* [x] `h-vialib` - https://github.com/hypothesis/h-vialib/issues/26
* [x] `h-checkmatelib` - https://github.com/hypothesis/checkmatelib/issues/10

We will need to upgrade / investigate the following:

_Note: all of these might be solved by using `npm` based tools instead: https://github.com/hypothesis/via3/pull/454_

* [x] `rjsmin` 
* [x] `htmlmin`
* [x] `rcssmin`

Also maybe (less important as it's in dev):

* [x] `pyramid_ipython` - I've removed this for now as I can't see what it does. We can put it back if it's important?

![app_via3](https://user-images.githubusercontent.com/7131143/115886410-cd115d80-a448-11eb-8c74-b22153e6838c.png)

**Comment by seanh** [comment]
It looks like `rjsmin`, `rcssmin` and `htmlmin` are only used by the `build` environment and, for some reason, `lint`. I don't think `build` has to use the same version of Python as is used for production / the dev server / the tests. If necessary it can use a different version of Python (and `Makefile` can just run `tox -qe py36-build`). The only problem is that those build dependencies are also used by the `lint` environment, so we might have to remove them from `lint` and then ignore some PyLint warnings caused by PyLint no longer knowing that `rjsmin`, `rcssmin` and `htmlmin` exist.

Of course if `build` can also be upgraded to the same Python version as everything else that'll be simpler
